version: 2.0

jobs:
  Python2:
    perform_black_check: false
    docker:
      - image: circleci/python:2.7.15
    steps:
      - checkout
      - run: sudo pip install -r requirements.txt
      - run: sudo pip install flake8 pytest
      - run: python --version ; pip --version ; pwd ; ls -l
      # stop the build if there are Python syntax errors or undefined names
      - run: flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
      # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
      - run: flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      #- run: pytest # test_s2gs test_replays
      - run: python -m unittest discover test_s2gs
      - run: python -m unittest discover test_replays



  Python3:
    perform_black_check: true
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: sudo pip install -r requirements.txt
      - run: sudo pip install flake8 pytest black
      - run: python --version ; pip --version ; pwd ; ls -l
      # stop the build if there are Python syntax errors or undefined names
      - run: flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
      # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
      - run: flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - run: black . --check
      #- run: pytest # test_s2gs test_replays
      - run: python -m unittest discover test_s2gs
      - run: python -m unittest discover test_replays


workflows:
  version: 2
  build:
    jobs:
      - Python2
      - Python3
